name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check Python version
      run: python --version

    # Run linting (TODO: fix linting failures and then uncomment this step)
    #- name: Lint with flake8
    #  run: |
    #     pip install flake8
    #     flake8 .

    # Future: Run tests (what framework will we use?)
    # - name: Run tests
    #   run: |
    #     pytest
    #     # or any other test command
